version: '2'

services:

  sbc:
    container_name: sbc
    command: npm run start:debug
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    ports:
      - "5000:3000"
    volumes:
      - "./:/app"
    links:
      - sbcmmysql


  sbcmmysql:
    container_name: sbcmmysql
    image: mysql:5.7.30
    ports:
      - "6000:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: sbcmmysql
      MYSQL_DBNAME: sbc
      MYSQL_USER: root
      MYSQL_PASSWORD: root